name: CI

on: [push, pull_request]

env:
  # It just checks for a valid URL, so any valid URL works
  DATABASE_URL: "https://fake.com"
  NEXTAUTH_SECRET: "fake_secret"
  NEXTAUTH_URL: "https://fake.com"
  GITHUB_CLIENT_ID: "fake_client_id"
  GITHUB_CLIENT_SECRET: "fake_client_secret"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint
